name: Build and Test
on:
  push:
    branches:
      - 'master'
jobs:
  build:
    name: Build ${{ matrix.os.name }}
    strategy:
      matrix:
        os:
          - name: Ubuntu
            runner: ubuntu-latest
          - name: Windows
            runner: windows-latest
          - name: macOS
            runner: macos-latest
    runs-on: ${{ matrix.os.runner }}
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
