name: Publish release assets
on:
  push:
    tags:
      - 'v[0-9]+.*'
jobs:
  publish:
    name: Publish
    strategy:
      matrix:
        runtime:
          - win-x64
          - win-x86
          - linux-x64
          - osx-x64
        self-contained: ['true', 'false']
    runs-on: ubuntu-latest
    env:
      release-name: cg-singlefile-for-cpp-${{ github.ref_name }}-${{ matrix.runtime }}${{ contains(matrix.self-contained, 'true') && '-self-contained' || '' }}
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
    - name: Publish
      run: >-
        dotnet publish cg-singlefile-for-cpp/cg-singlefile-for-cpp.csproj
        -c Release -r ${{ matrix.runtime }}
        /p:PublishSelfContained=${{ matrix.self-contained }},PublishTrimmed=${{ matrix.self-contained }}
        -o bin
    - name: Zip bin folder
      run: |
        cd bin
        zip -r ${{ env.release-name }}.zip *
        cd ..
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: bin/${{ env.release-name }}.zip